# Generated by Django 4.1 on 2022-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('depto_ocurrencia', models.CharField(max_length=50)),
                ('evento', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('fuente_notificacion', models.CharField(max_length=50)),
                ('mun_ocurrencia', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('numero_situaciones', models.IntegerField()),
                ('referencia', models.CharField(max_length=50)),
                ('seguimiento', models.CharField(max_length=200)),
                ('situacion_reportada', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('archivos_adjuntos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('semana', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('fecha_ocurrencia', models.DateField()),
                ('fecha_notificacion', models.DateField()),
                ('fuente_notificacion', models.CharField(max_length=50)),
                ('depto_ocurrencia', models.CharField(max_length=50)),
                ('mun_ocurrencia', models.CharField(max_length=50)),
                ('lugar_ocurrencia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('situacion_reportada', models.CharField(max_length=50)),
                ('evento', models.CharField(max_length=50)),
                ('grupo_funcional', models.CharField(max_length=50)),
                ('poblacion_afectada', models.CharField(max_length=50)),
                ('criterio_riesgo', models.CharField(max_length=50)),
                ('informe_iec', models.CharField(max_length=5)),
                ('fecha_iec', models.DateField()),
                ('numero_de_contactos', models.IntegerField()),
                ('numero_de_enfermos', models.IntegerField()),
                ('tasa_de_ataque', models.IntegerField()),
                ('numero_de_expuestos', models.IntegerField()),
                ('numero_de_fallecidos', models.IntegerField()),
                ('muestras', models.CharField(max_length=10)),
                ('numero_de_muestras', models.IntegerField()),
                ('fecha_toma_de_muestras', models.DateField()),
                ('fecha_envio_de_muestras', models.DateField()),
                ('tipo_de_muestra', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=50)),
                ('fecha_envio_al_ins', models.DateField()),
                ('se_realiza_sar', models.CharField(max_length=50)),
                ('sitrep', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_de_cierre', models.DateField()),
                ('conclusion', models.CharField(max_length=20)),
                ('recomendacion', models.CharField(max_length=50)),
                ('seguimiento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('codigo_evento', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('semana', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('titulo_noticia', models.CharField(max_length=200)),
                ('fecha_ocurrencia', models.DateField()),
                ('resumen_noticia', models.CharField(max_length=1000)),
                ('fuente_notificacion', models.CharField(max_length=50)),
                ('enlace_noticia', models.CharField(max_length=200)),
                ('evento', models.CharField(max_length=50)),
                ('grupo_funcional', models.CharField(max_length=50)),
                ('depto_ocurrencia', models.CharField(max_length=50)),
                ('mun_ocurrencia', models.CharField(max_length=50)),
                ('poblacion_afectada', models.CharField(max_length=50)),
                ('criterio_riesgo', models.CharField(max_length=50)),
                ('confirmacion', models.CharField(max_length=5)),
                ('seguimiento', models.CharField(max_length=200)),
            ],
        ),
    ]
